### PR TITLE
Fix an osx internal assertion in NSWindow - ensure the C string is null terminated.

### PR DESCRIPTION
**Pull request by glennw**

### CODE REVIEW

**Comment by SSheldon** [comment]
I'd recommend switching to the `initWithBytes:length:encoding:` method, which is pretty easy to safely wrap from Rust: https://github.com/SSheldon/rust-objc/blob/e55aec485ad2b551be65ed658ae82d0997b3eb3a/foundation/string.rs#L52-61

**Comment by bjz** [comment]
I'm going to r+ this, but please post a follow up PR with @SSheldon's fix.

**Comment by glennw** [comment]
@SSheldon and @bjz Sure, thanks for the tip, I don't know cocoa very well. Opened a follow up issue here https://github.com/servo/rust-cocoa/issues/73

**Pull request merged**
